### PR TITLE
Allow binary responses in `getObject`

### LINKED ISSUE #105: S3Client.getObject does not work for binary data
On top of #45, the `S3Client` cannot be used to download a binary file from S3!

as I'm sure you are aware, if you have `discardResponseBodies=false`
there’s a  `Params.responseType` that you can pass to a call to k6's `http` like
```
  const res = http.get('https://httpbin.test.k6.io/bytes/10', {
    responseType: 'binary',
  });
```
 and that controls whether  `res.body` is a `string` or an `ArrayBuffer`.

however since the `S3Client` code does not pass in a `responseType` in this code 
https://github.com/grafana/k6-jslib-aws/blob/f6b5dce3efe25d981836ae0ad8038f3866323d23/src/internal/s3.ts#L185-L187
then that means it defaults to `responseType: 'text'` and that means

> - text: k6 will return it as a string. This might not be what you want in cases of binary data as the conversation to UTF-16 will probably break it.
> This is also the default if [discardResponseBodies](https://k6.io/docs/using-k6/k6-options/reference) is set to false or not set at all.

We need a way to either pass thru or hard-code a `responseType: 'binary'` for the k6 `http` client call in `getObject`.
Do you have a preference on how that might be implemented?

### PR DESCRIPTION
**Pull request by KOConchobhair**
Fixes #105

### CODE REVIEW

**Comment by oleiade** [comment]
See design considerations in #105.

**Comment by oleiade** [comment]
Hey @KOConchobhair 👋🏻 

We have discussed it internally, and the maintainers agree we'd prefer the approach depicted in https://github.com/grafana/k6-jslib-aws/issues/105#issuecomment-2173486709.

If you have the capacity, we'd greatly appreciate it if you could align this PR's design. Otherwise, that's also fine, and we'd likely proceed with it ourselves. Just let us know 🙇🏻

**Comment by KOConchobhair** [comment]
Sorry for the delay, I was a little confused by your suggestion in https://github.com/grafana/k6-jslib-aws/issues/105#issuecomment-2173486709 since `Accept` is not even one of the headers listed at the S3 link. But i guess you are saying that it gives you the path to support them in the future.

I will just state that this is not an S3 API problem at all, its a very specific problem related to the inner workings of k6. So specifying an 1Accept1 header that doesn't actually change how S3 responds and only impacts the parsing on the k6 side is a little odd (but again, its putting in place the API for future stuff which is nice to not break the API again). I think this makes it _a little_ difficult to support all types of binary headers (so we'll have to add images too, i guess `image/*`)

but this is a blocker for me using k6 how I want in my project so I'll implement since I'd really like to continue using k6 
😄

**Comment by oleiade** [comment]
We know this is not an official AWS header, but it is an official HTTP header, and it indicates to the server the response type you expect to receive back, so it is a good fit.

This is also why we call it `additionalHeaders` and not `requestParameterHeaders`: It allows you to add any headers to the request, not only AWS ones. Not being able to set the underlying HTTP request's headers has caused a couple of issues in this project over time. It is actually a design we could probably extend to the AWSClient itself to a certain extent. 

This way of doing it feels like a better mitigation than aligning with the `responseType` approach of the k6 HTTP client, which is not ideal in my experience and, as we're redesigning our HTTP client, might go away in the future.

Regarding the different MIME types supported, my assumption was that using the `Accept` header in this case was meant more as a convention than a strict requirement we would expect S3 to comply with: " If you set the Accept header, the S3 client will return binary content, otherwise text."

I'll look at the official support AWS headers to see if another candidate I might have overlooked shows up 🙇🏻

**Comment by KOConchobhair** [comment]
> Regarding the different MIME types supported, my assumption was that using the `Accept` header in this case was meant more as a convention than a strict requirement we would expect S3 to comply with: " If you set the Accept header, the S3 client will return binary content, otherwise text."

Just thinking from a k6 user perspective though, giving something as broad as an `Accept` header in this API which allows me to set it to `{ 'Accept': 'application/json' }` and then have k6 interpret as binary, that would be confusing to the k6 script writer IMO.

**Comment by oleiade** [comment]
For clarification, as mentioned in my initial comment only "Accept: application/octet-stream" would lead to the content being treated as binary.

**Comment by KOConchobhair** [comment]
oh duh, okay so rephrased  "If you set the Accept header (**to application/octect-stream**), the S3 client will return binary content, otherwise text."

**Comment by oleiade** [comment]
Hey @KOConchobhair 👋🏻

Will you have capacity to update the PR according to our discussions? 🙇🏻 

PS: I will be away for the next two weeks, but @joanlopez will be able to follow-up on this in the meantime.

**Comment by KOConchobhair** [comment]
this is still on my list but fell down the priority a bit, hopefully i can get back to it this week

**Comment by oleiade** [comment]
Closing in favor of #113

**Pull request closed without merging**
